/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI_NhanVien;

import UI_QuanLy.TaiKhoan;
import UI_QuanLy.TrangChu;
import java.awt.Color;
import javax.swing.JPanel;
import util.ImageUtill;

/**
 *
 * @author Admin
 */
public class UI_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form UI_NhanVien
     */
    private JPanel pChucNang;
    public UI_NhanVien() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ImageUtill imageUtil = new ImageUtill();
        imageUtil.addImage(lblogoQL, "working.png", 90, 90);
        
        lbTrangChu.setBackground(new Color(8, 86, 168));
        lbTrangChu.setForeground(Color.WHITE);
        pChucNang = new TrangChu();
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate(); 
    }
    
     private void setBlackColor(){
        lbTrangChu.setForeground(Color.BLACK);
        lbChamCong.setForeground(Color.BLACK);
        lbNhanViec.setForeground(Color.BLACK);
        lbXinNghiPhep.setForeground(Color.BLACK);
        lbLuongThang.setForeground(Color.BLACK);
        lbTaiKhoan.setForeground(Color.BLACK);
    }
    private void setWhiteBackground(){
        lbTrangChu.setBackground(Color.WHITE);
        lbChamCong.setBackground(Color.WHITE);
        lbNhanViec.setBackground(Color.WHITE);
        lbXinNghiPhep.setBackground(Color.WHITE);
        lbLuongThang.setBackground(Color.WHITE);
        lbTaiKhoan.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbXinNghiPhep = new javax.swing.JLabel();
        lbLuongThang = new javax.swing.JLabel();
        lbTaiKhoan = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        lblogoQL = new javax.swing.JLabel();
        lbTrangChu = new javax.swing.JLabel();
        lbChamCong = new javax.swing.JLabel();
        lbNhanViec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbXinNghiPhep.setBackground(new java.awt.Color(255, 255, 255));
        lbXinNghiPhep.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbXinNghiPhep.setText("  Xin nghỉ phép");
        lbXinNghiPhep.setOpaque(true);
        lbXinNghiPhep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXinNghiPhepMouseClicked(evt);
            }
        });

        lbLuongThang.setBackground(new java.awt.Color(255, 255, 255));
        lbLuongThang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbLuongThang.setText("   Lương tháng");
        lbLuongThang.setOpaque(true);
        lbLuongThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLuongThangMouseClicked(evt);
            }
        });

        lbTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lbTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTaiKhoan.setText("  Tài khoản");
        lbTaiKhoan.setOpaque(true);
        lbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTaiKhoanMouseClicked(evt);
            }
        });

        pnMain.setLayout(new java.awt.BorderLayout());

        lblogoQL.setBackground(new java.awt.Color(255, 255, 255));

        lbTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        lbTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTrangChu.setText("  Trang chủ");
        lbTrangChu.setOpaque(true);
        lbTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTrangChuMouseClicked(evt);
            }
        });

        lbChamCong.setBackground(new java.awt.Color(255, 255, 255));
        lbChamCong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbChamCong.setText("  Chấm công");
        lbChamCong.setOpaque(true);
        lbChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbChamCongMouseClicked(evt);
            }
        });

        lbNhanViec.setBackground(new java.awt.Color(255, 255, 255));
        lbNhanViec.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbNhanViec.setText("  Nhận việc");
        lbNhanViec.setOpaque(true);
        lbNhanViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanViecMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLuongThang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbXinNghiPhep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(lbNhanViec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblogoQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblogoQL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbNhanViec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbXinNghiPhep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbLuongThang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbXinNghiPhepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXinNghiPhepMouseClicked
        // TODO add your handling code here:
        setBlackColor();
        setWhiteBackground();
        lbXinNghiPhep.setBackground(new Color(8, 86, 168));
        lbXinNghiPhep.setForeground(Color.WHITE);

        pChucNang = new XinNghiPhep();
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate();
    }//GEN-LAST:event_lbXinNghiPhepMouseClicked

    private void lbLuongThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLuongThangMouseClicked
        // TODO add your handling code here:
        setBlackColor();
        setWhiteBackground();
        lbLuongThang.setBackground(new Color(8, 86, 168));
        lbLuongThang.setForeground(Color.WHITE);

        pChucNang = new LuongThang();
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate();
    }//GEN-LAST:event_lbLuongThangMouseClicked

    private void lbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTaiKhoanMouseClicked
        // TODO add your handling code here:
        setBlackColor();
        setWhiteBackground();
        lbTaiKhoan.setBackground(new Color(8, 86, 168));
        lbTaiKhoan.setForeground(Color.WHITE);

        pChucNang = new TaiKhoan(this);
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate();
    }//GEN-LAST:event_lbTaiKhoanMouseClicked

    private void lbTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangChuMouseClicked
        // TODO add your handling code here:
        setBlackColor();
        setWhiteBackground();
        lbTrangChu.setBackground(new Color(8, 86, 168));
        lbTrangChu.setForeground(Color.WHITE);

        pChucNang = new TrangChu();
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate();
    }//GEN-LAST:event_lbTrangChuMouseClicked

    private void lbChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbChamCongMouseClicked
        // TODO add your handling code here:
        setBlackColor();
        setWhiteBackground();
        lbChamCong.setBackground(new Color(8, 86, 168));
        lbChamCong.setForeground(Color.WHITE);

        pChucNang = new ChamCong();
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate();
    }//GEN-LAST:event_lbChamCongMouseClicked

    private void lbNhanViecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanViecMouseClicked
        // TODO add your handling code here:
        setBlackColor();
        setWhiteBackground();
        lbNhanViec.setBackground(new Color(8, 86, 168));
        lbNhanViec.setForeground(Color.WHITE);

        pChucNang = new NhanViec();
        pnMain.removeAll();
        pnMain.add(pChucNang);
        pnMain.validate();
    }//GEN-LAST:event_lbNhanViecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbChamCong;
    private javax.swing.JLabel lbLuongThang;
    private javax.swing.JLabel lbNhanViec;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTrangChu;
    private javax.swing.JLabel lbXinNghiPhep;
    private javax.swing.JLabel lblogoQL;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
