/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_QuanLy;

import ChucNang_DuyetNghiPhep.Duyet;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class DuyetNghiPhep extends javax.swing.JPanel {

    /**
     * Creates new form DuyetNghiPhep
     */
    public DuyetNghiPhep() {
        initComponents();
        
        pnNhanVienNghiPhep.setLayout(new BoxLayout(pnNhanVienNghiPhep, BoxLayout.Y_AXIS));
        pnNhanVienNghiPhep.setBackground(Color.WHITE);
        
        lbTieude.setBackground(new Color(8, 86, 168));
        lbTieude.setForeground(Color.WHITE);
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        
        displayEmployees();
        
        
    }
    
     
     public void addNhanVienNghiPhepPanel(String tenNhanVien, String maNhanVien) {
        
        pnNhanVienNghiPhep.add(Box.createVerticalStrut(5));
        // Tạo JPanel cho từng nhân viên
        JPanel nhanVienPanel = new JPanel();
        nhanVienPanel.setLayout(new BoxLayout(nhanVienPanel, BoxLayout.Y_AXIS));
        nhanVienPanel.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(Color.GRAY), 
        BorderFactory.createEmptyBorder(3, 3, 3, 3) // Tạo khoảng cách bên trong panel
        ));
        Color originalBackground = nhanVienPanel.getBackground();


        // Tạo JLabel cho thông tin nhân viên (Tên và Mã nhân viên trên cùng một dòng)
        JLabel employeeLabel = new JLabel("  " + tenNhanVien + " - " + maNhanVien);

         Font currentFont = employeeLabel.getFont();
    employeeLabel.setFont(new Font(currentFont.getFontName(),
            currentFont.getStyle(),
            currentFont.getSize() + 6)
    );

        // Thêm JLabel vào JPanel của nhân viên
        nhanVienPanel.add(employeeLabel);

        // Tạo khoảng cách giữa các panel nhân viên bằng EmptyBorder
        nhanVienPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        nhanVienPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, nhanVienPanel.getPreferredSize().height));

        //
        // Thêm sự kiện bấm vào nhanVienPanel
        nhanVienPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Thao tác khi nhấn vào JPanel nhân viên
                Duyet d = new Duyet();
                d.setVisible(true);        
                }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
            nhanVienPanel.setBackground(new Color(200, 200, 200)); // Đổi màu khi di chuột qua
            }

            @Override
             public void mouseExited(java.awt.event.MouseEvent evt) {
               nhanVienPanel.setBackground(originalBackground); // Trả lại màu nền ban đầu khi rời chuột
            }
            });
        //
    
        // Thêm JPanel của nhân viên vào pnDanhSachNhanVien
        pnNhanVienNghiPhep.add(nhanVienPanel); 
        pnNhanVienNghiPhep.revalidate(); // Cập nhật lại layout
        pnNhanVienNghiPhep.repaint(); // Vẽ lại để hiển thị thay đổi
        pnNhanVienNghiPhep.add(Box.createVerticalStrut(5));
}
    public void displayEmployees(){
//         // Lấy danh sách nhân viên từ cơ sở dữ liệu
//    List<Employee> employees = fetchEmployeesFromDatabase();
//
//    // Hiển thị từng nhân viên trong JScrollPane
//    for (Employee employee : employees) {
//        addEmployeePanel(employee.name, employee.position, employee.id);
//    }
    
        addNhanVienNghiPhepPanel("Lê Công Bảo Ngọc", "CT060129");
        addNhanVienNghiPhepPanel("Mai Văn Tĩnh", "CT060143");
        addNhanVienNghiPhepPanel("Đỗ Mạnh Nghĩa", "CT060128");
        addNhanVienNghiPhepPanel("Nguyễn Văn Thông", "CT060339");
        addNhanVienNghiPhepPanel("Tĩnh Súc Vật", "SVSVSVSV");
        addNhanVienNghiPhepPanel("Tĩnh Ăn ĐB", "ĐBĐBĐB");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDuyetNghiPhep = new javax.swing.JPanel();
        lbTieude = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnNhanVienNghiPhep = new javax.swing.JPanel();
        buttonDarkBlue1 = new util.ButtonDarkBlue();

        lbTieude.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTieude.setText("Duyệt nghỉ phép");
        lbTieude.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Danh sách các nhân viên nghỉ phép");

        javax.swing.GroupLayout pnNhanVienNghiPhepLayout = new javax.swing.GroupLayout(pnNhanVienNghiPhep);
        pnNhanVienNghiPhep.setLayout(pnNhanVienNghiPhepLayout);
        pnNhanVienNghiPhepLayout.setHorizontalGroup(
            pnNhanVienNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        pnNhanVienNghiPhepLayout.setVerticalGroup(
            pnNhanVienNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnNhanVienNghiPhep);

        buttonDarkBlue1.setText("Làm mới");
        buttonDarkBlue1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        javax.swing.GroupLayout pnDuyetNghiPhepLayout = new javax.swing.GroupLayout(pnDuyetNghiPhep);
        pnDuyetNghiPhep.setLayout(pnDuyetNghiPhepLayout);
        pnDuyetNghiPhepLayout.setHorizontalGroup(
            pnDuyetNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDuyetNghiPhepLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDarkBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(pnDuyetNghiPhepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDuyetNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDuyetNghiPhepLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 356, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lbTieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnDuyetNghiPhepLayout.setVerticalGroup(
            pnDuyetNghiPhepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDuyetNghiPhepLayout.createSequentialGroup()
                .addComponent(lbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonDarkBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDuyetNghiPhep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDuyetNghiPhep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonDarkBlue buttonDarkBlue1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTieude;
    private javax.swing.JPanel pnDuyetNghiPhep;
    private javax.swing.JPanel pnNhanVienNghiPhep;
    // End of variables declaration//GEN-END:variables
}
