/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_QuanLy;

import ChucNang_QuanLyNhanVien.SuaThongTinNhanVien;
import ChucNang_QuanLyNhanVien.XemDanhSachNhanVien;
import ChucNang_QuanLyNhanVien.XemThongTinNhanVien;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import util.ImageUtill;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JPanel {
    

    /**
     * Creates new form QuanLyNhanVien
     */
    
    private JPanel pChucNangQL;
    
    public QuanLyNhanVien() {
        initComponents();
        lbTieude.setBackground(new Color(8, 86, 168));
        lbTieude.setForeground(Color.WHITE);
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        
        lbTieude2.setBackground(new Color(8, 86, 168));
        lbTieude2.setForeground(Color.WHITE);
        lbTieude2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude2.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        
        pnChucNangQLNV.setLayout(new BoxLayout(pnChucNangQLNV, BoxLayout.Y_AXIS));
        pnChucNangQLNV.setBackground(Color.WHITE);
       
        pChucNangQL = new XemDanhSachNhanVien();
        pnChucNangQLNV.removeAll();
        pnChucNangQLNV.add(pChucNangQL);
        pnChucNangQLNV.validate(); 
        
        ImageUtill imageUtil = new ImageUtill();
        imageUtil.addImage(lbMagnifier, "magnifier.png", 20, 20);
      
    }
    
    
    
    
    public void showEmployeeOptions(String employeeName) {
        // Tạo các lựa chọn cho người dùng
        String[] options = {"Xem thông tin", "Sửa thông tin", "Xóa nhân viên"};

        // Hiển thị hộp thoại với các lựa chọn
        int choice = JOptionPane.showOptionDialog(
            null, // Component cha, nếu là null sẽ xuất hiện ở giữa màn hình
            "Chọn hành động cho nhân viên: " + employeeName, // Nội dung thông báo
            "Tùy chọn cho nhân viên", // Tiêu đề của hộp thoại
            JOptionPane.DEFAULT_OPTION, // Không có nút mặc định
            JOptionPane.INFORMATION_MESSAGE, // Loại thông báo
            null, // Icon (có thể đặt icon nếu muốn)
            options, // Các lựa chọn
            options[0] // Lựa chọn mặc định
        );

        // Xử lý sự kiện dựa trên lựa chọn của người dùng
        switch (choice) {
            case 0:
                System.out.println("Bạn đã chọn: Xem thông tin cho nhân viên " + employeeName);
                // Thêm mã để hiển thị thông tin chi tiết của nhân viên
                XemThongTinNhanVien xttnv = new XemThongTinNhanVien();
                xttnv.setVisible(true);
                
                ;
                
                break;
            case 1:
                System.out.println("Bạn đã chọn: Sửa thông tin cho nhân viên " + employeeName);
                // Thêm mã để sửa thông tin nhân viên
                SuaThongTinNhanVien sttnv = new SuaThongTinNhanVien();
                sttnv.setVisible(true);
               
                break;
            case 2:
                int confirm = JOptionPane.showConfirmDialog(
                    null, 
                    "Bạn có chắc chắn muốn xóa nhân viên " + employeeName + " không?", 
                    "Xác nhận xóa",
                    JOptionPane.OK_CANCEL_OPTION, 
                    JOptionPane.WARNING_MESSAGE
                );
                if (confirm == JOptionPane.OK_OPTION) {
                    System.out.println("Nhân viên " + employeeName + " đã được xóa.");
                    // Thêm mã để xóa nhân viên
                } else {
                    System.out.println("Hủy xóa nhân viên " + employeeName);
                }
                break;
            default:
                System.out.println("Không có lựa chọn nào được chọn");
                break;
    }
      
}
   
    public void ArrowBack() {
        pnChucNangQLNV.setLayout(new BoxLayout(pnChucNangQLNV, BoxLayout.Y_AXIS));
        pnChucNangQLNV.setBackground(Color.WHITE);
        pChucNangQL = new XemDanhSachNhanVien();
        pnChucNangQLNV.removeAll();
        pnChucNangQLNV.add(pChucNangQL);
        pnChucNangQLNV.validate();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnQuanLyNhanVien = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbTieude = new javax.swing.JLabel();
        lbTenChucNang = new javax.swing.JLabel();
        btnLamMoi = new util.ButtonDarkBlue();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnChucNangQLNV = new javax.swing.JPanel();
        lbMagnifier = new javax.swing.JLabel();
        tfTimKiemNhanVien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbTieude2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTaiKhoan = new javax.swing.JTextField();
        tfMatKhau = new javax.swing.JTextField();
        lbHoTen = new javax.swing.JLabel();
        lbMaNhanVien = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        lbSoCCCD = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSĐT = new javax.swing.JLabel();
        btnThemNhanVien = new util.ButtonDarkBlue();
        tfHoTen = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        tfSoCCCD = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfSĐT = new javax.swing.JTextField();
        tfMaNhanVien = new javax.swing.JTextField();
        tfNgaySinh = new javax.swing.JTextField();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lbTieude.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTieude.setText("Quản lý nhân viên");
        lbTieude.setOpaque(true);

        lbTenChucNang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbTenChucNang.setText("Danh sách nhân viên");

        btnLamMoi.setText("Làm mới");
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        pnChucNangQLNV.setLayout(new java.awt.BorderLayout());
        jScrollPane2.setViewportView(pnChucNangQLNV);

        tfTimKiemNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tfTimKiemNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbTenChucNang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(tfTimKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMagnifier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbTenChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMagnifier, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfTimKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý nhân viên", jPanel1);

        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lbTieude2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTieude2.setText("Thêm nhân viên");
        lbTieude2.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Tài khoản: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mật khẩu: ");

        tfTaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfMatKhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbHoTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbHoTen.setText("Họ tên: ");

        lbMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMaNhanVien.setText("Mã nhân viên: ");

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbGioiTinh.setText("Giới tính: ");

        lbNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbNgaySinh.setText("Ngày sinh: ");

        lbDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDiaChi.setText("Địa chỉ: ");

        lbSoCCCD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbSoCCCD.setText("Số CCCD: ");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbEmail.setText("Email: ");

        lbSĐT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbSĐT.setText("SĐT: ");

        btnThemNhanVien.setText("Thêm nhân viên");

        tfHoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfDiaChi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfSoCCCD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfSĐT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfMaNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfNgaySinh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(rbtNam);
        rbtNam.setText("Nam");

        buttonGroup1.add(rbtNu);
        rbtNu.setText("Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTieude2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbtNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtNu))
                                    .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbSoCCCD)
                                    .addComponent(lbDiaChi)
                                    .addComponent(lbSĐT)
                                    .addComponent(lbEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbTieude2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfTaiKhoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfMatKhau)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoTen)
                            .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoCCCD)
                            .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaNhanVien))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtNam)
                        .addComponent(rbtNu))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDiaChi)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbGioiTinh))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgaySinh)
                    .addComponent(lbSĐT)
                    .addComponent(tfSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Thêm nhân viên mới", jPanel2);

        javax.swing.GroupLayout pnQuanLyNhanVienLayout = new javax.swing.GroupLayout(pnQuanLyNhanVien);
        pnQuanLyNhanVien.setLayout(pnQuanLyNhanVienLayout);
        pnQuanLyNhanVienLayout.setHorizontalGroup(
            pnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        pnQuanLyNhanVienLayout.setVerticalGroup(
            pnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.ButtonDarkBlue btnLamMoi;
    private util.ButtonDarkBlue btnThemNhanVien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JLabel lbMagnifier;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSoCCCD;
    private javax.swing.JLabel lbSĐT;
    private javax.swing.JLabel lbTenChucNang;
    private javax.swing.JLabel lbTieude;
    private javax.swing.JLabel lbTieude2;
    private javax.swing.JPanel pnChucNangQLNV;
    private javax.swing.JPanel pnQuanLyNhanVien;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfMaNhanVien;
    private javax.swing.JTextField tfMatKhau;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfSoCCCD;
    private javax.swing.JTextField tfSĐT;
    private javax.swing.JTextField tfTaiKhoan;
    private javax.swing.JTextField tfTimKiemNhanVien;
    // End of variables declaration//GEN-END:variables
}
