/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ChucNang_QuanLyNhanVien;

import UI_QuanLy.QuanLyNhanVien;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class XemDanhSachNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form XemDanhSachNhanVien
     */
    public XemDanhSachNhanVien() {
        initComponents();
        pnDanhSachNhanVien.setLayout(new BoxLayout(pnDanhSachNhanVien, BoxLayout.Y_AXIS));
        pnDanhSachNhanVien.setBackground(Color.WHITE);
        displayEmployees();
    }
    
    public void addEmployeePanel(String tenNhanVien, String maNhanVien) {
        
        pnDanhSachNhanVien.add(Box.createVerticalStrut(5));
        // Tạo JPanel cho từng nhân viên
        JPanel nhanVienPanel = new JPanel();
        nhanVienPanel.setLayout(new BoxLayout(nhanVienPanel, BoxLayout.Y_AXIS));
        nhanVienPanel.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(Color.GRAY), 
        BorderFactory.createEmptyBorder(3, 3, 3, 3) // Tạo khoảng cách bên trong panel
        ));
        Color originalBackground = nhanVienPanel.getBackground();


        // Tạo JLabel cho thông tin nhân viên (Tên và Mã nhân viên trên cùng một dòng)
        JLabel employeeLabel = new JLabel("  " + tenNhanVien + " - " + maNhanVien);

        
         Font currentFont = employeeLabel.getFont();
    employeeLabel.setFont(new 
        Font(currentFont.getFontName(), 
                currentFont.getStyle(), 
                currentFont.getSize() + 6)
    );
    

        // Thêm JLabel vào JPanel của nhân viên
        nhanVienPanel.add(employeeLabel);

        // Tạo khoảng cách giữa các panel nhân viên bằng EmptyBorder
        nhanVienPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        nhanVienPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, nhanVienPanel.getPreferredSize().height));

        //
        // Thêm sự kiện bấm vào nhanVienPanel
        nhanVienPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Thao tác khi nhấn vào JPanel nhân viên
                QuanLyNhanVien quanLyNhanVien = new QuanLyNhanVien();
                quanLyNhanVien.showEmployeeOptions(tenNhanVien);
                }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
            nhanVienPanel.setBackground(new Color(200, 200, 200)); // Đổi màu khi di chuột qua
            }

            @Override
             public void mouseExited(java.awt.event.MouseEvent evt) {
               nhanVienPanel.setBackground(originalBackground); // Trả lại màu nền ban đầu khi rời chuột
            }
            });
        //
        
    
        // Thêm JPanel của nhân viên vào pnDanhSachNhanVien
        pnDanhSachNhanVien.add(nhanVienPanel); 
        pnDanhSachNhanVien.revalidate(); // Cập nhật lại layout
        pnDanhSachNhanVien.repaint(); // Vẽ lại để hiển thị thay đổi
        pnDanhSachNhanVien.add(Box.createVerticalStrut(5));
}
    public void displayEmployees(){
//         // Lấy danh sách nhân viên từ cơ sở dữ liệu
//    List<Employee> employees = fetchEmployeesFromDatabase();
//
//    // Hiển thị từng nhân viên trong JScrollPane
//    for (Employee employee : employees) {
//        addEmployeePanel(employee.name, employee.position, employee.id);
//    }
    
        addEmployeePanel("Lê Công Bảo Ngọc", "CT060129");
        addEmployeePanel("Mai Văn Tĩnh", "CT060143");
        addEmployeePanel("Đỗ Mạnh Nghĩa", "CT060128");
        addEmployeePanel("Nguyễn Văn Thông", "CT060339");
        addEmployeePanel("Tĩnh Súc Vật", "SVSVSVSV");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDanhSachNhanVien = new javax.swing.JPanel();

        javax.swing.GroupLayout pnDanhSachNhanVienLayout = new javax.swing.GroupLayout(pnDanhSachNhanVien);
        pnDanhSachNhanVien.setLayout(pnDanhSachNhanVienLayout);
        pnDanhSachNhanVienLayout.setHorizontalGroup(
            pnDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        pnDanhSachNhanVienLayout.setVerticalGroup(
            pnDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDanhSachNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDanhSachNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnDanhSachNhanVien;
    // End of variables declaration//GEN-END:variables
}
